version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: AWS configure
          command: |
            aws configure list
      - run: 
          name: Install Packer
          command: |
            wget https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
            unzip packer_1.5.4_linux_amd64.zip
            sudo mv packer /usr/local/bin
      - run:
          name: Validate Packer JSON
          command: packer validate packer.json
      - run:
          name: Build Packer
          command: packer build packer.json

workflows:
  version: 2

  packer_buid:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master