version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run: 
          name: Validate Packer JSON
          command: packer validate packer.json
      - run:
          name: Build Packer
          command: packer build packer.json

workflows:
  version: 2

  packer_buid:
    jobs:
      - build
