version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circleci
      - run:
          aws configure list
      - run: 
          name: Validate Packer JSON
          command: packer validate packer.json
      - run:
          name: Build Packer
          command: packer build packer.json

workflows:
  version: 2

  packer_buid:
    jobs:
      - build:
          filters:
            branches:
              only:
                - a7